image: node:12.19

clone:
  depth: full
pipelines:
  branches:
    master:
      - step:
          name: Build
          caches:
            - node
          script: #installation
            - npm install
      # - step:
      #     name: Deploy to Digital Ocean
      #     deployment: test
      #     trigger: manual
      #     caches:
      #       - nodecustom
      #       - yarncustom
      #     script:
      #       - yarn
      #       - yarn build
      #       - pipe: atlassian/rsync-deploy:0.4.4
      #         variables:
      #           USER: $SSH_USER
      #           SERVER: $SSH_HOST
      #           REMOTE_PATH: '~/app/gran-api/'
      #           LOCAL_PATH: '${BITBUCKET_CLONE_DIR}/'
      #           SSH_PORT: $SSH_PORT # Optional.
      #           EXTRA_ARGS: '--exclude=node_modules/*' # Optional.
      #           DELETE_FLAG: 'false' # Optional.
      #           # SSH_KEY: '<string>' # Optional.
      #           # DEBUG: '<boolean>' # Optional.
      #       - pipe: atlassian/ssh-run:0.3.0
      #         variables:
      #           SSH_USER: $SSH_USER
      #           SERVER: $SSH_HOST
      #           COMMAND: 'deploy.sh'
      #           MODE: 'script' # Optional
      #           PORT: $SSH_PORT # Optional
      #           # SSH_KEY: '<string>' # Optional.
      #           # EXTRA_ARGS: '<string>' # Optional
      #           # ENV_VARS: '<string>' # Optional
      #           # DEBUG: '<string>' # Optional
      - step:
          name: Deploy to Staging
          deployment: staging
          script:
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_STAGING_APP.git HEAD
      - step:
          name: Deploy to Production
          deployment: production
          trigger: manual
          script:
            - git push https://heroku:$HEROKU_API_KEY_PROD@git.heroku.com/$HEROKU_PROD_APP.git HEAD
definitions:
  caches:
    nodecustom: ./node_modules
    yarncustom: /usr/local/share/.cache/yarn
